#include <include/gui/MochiUI.h>
#include <include/gui/Layout.hpp>
#include <include/gui/Components.hpp>
#include <include/gui/Theme.hpp>
#include <include/gui/TaskDialog.hpp>
#include <include/utils/FontManager/FontMgr.hpp>
#include <include/utils/Misc/ThemeSwitcher.hpp>

using namespace MochiUI;

FlexNode::Ptr CreateAppUI(int width, int height) {
    auto root = FlexNode::Row();
    root->style.backgroundColor = Theme::Background;
    root->style.widthMode = SizingMode::Flex;
    root->style.heightMode = SizingMode::Flex;

    auto sidebar = FlexNode::Column();
    sidebar->style.width = 250;
    sidebar->style.widthMode = SizingMode::Fixed;
    sidebar->style.heightMode = SizingMode::Flex;
    sidebar->style.backgroundColor = Theme::Sidebar;
    sidebar->style.padding = 10;
    sidebar->style.gap = 5;

    for(int i=1; i<=8; ++i) {
        auto item = std::make_shared<TextNode>();
        item->text = "Mochi Item " + std::to_string(i);
        item->style.height = 35;
        item->style.heightMode = SizingMode::Fixed;
        item->style.widthMode = SizingMode::Flex;
        item->style.backgroundColor = Theme::Card;
        item->style.borderRadius = 6;
        item->color = Theme::TextPrimary;
        item->fontSize = 14;
        sidebar->addChild(item);
    }

    auto mainContent = FlexNode::Column();
    mainContent->style.flex = 1.0f;
    mainContent->style.widthMode = SizingMode::Flex;
    mainContent->style.heightMode = SizingMode::Flex;
    mainContent->style.padding = 40;
    mainContent->style.gap = 20;

    auto header = std::make_shared<TextNode>();
    header->text = "MochiUI Framework";
    header->style.heightMode = SizingMode::Hug;
    header->style.widthMode = SizingMode::Hug;
    header->style.padding = 5;
    header->color = Theme::TextPrimary;
    header->fontSize = 42;
    mainContent->addChild(header);

    auto hugContainer = FlexNode::Row();
    hugContainer->style.heightMode = SizingMode::Hug;
    hugContainer->style.widthMode = SizingMode::Hug;
    hugContainer->style.backgroundColor = Theme::Accent;
    hugContainer->style.padding = 10;
    hugContainer->style.borderRadius = 10;
    hugContainer->style.gap = 10;

    auto hugText = std::make_shared<TextNode>();
    hugText->text = "Autogenerated Theme Applied!";
    hugText->style.widthMode = SizingMode::Hug;
    hugText->style.heightMode = SizingMode::Hug;
    hugText->color = Theme::TextPrimary;
    hugContainer->addChild(hugText);
    
    mainContent->addChild(hugContainer);

    // Add checkbox examples
    auto checkboxSection = FlexNode::Column();
    checkboxSection->style.widthMode = SizingMode::Hug;
    checkboxSection->style.heightMode = SizingMode::Hug;
    checkboxSection->style.gap = 12;
    checkboxSection->style.padding = 20;
    checkboxSection->style.backgroundColor = Theme::Card;
    checkboxSection->style.borderRadius = 8;

    auto sectionTitle = std::make_shared<TextNode>();
    sectionTitle->text = "Checkbox Components";
    sectionTitle->style.widthMode = SizingMode::Hug;
    sectionTitle->style.heightMode = SizingMode::Hug;
    sectionTitle->color = Theme::TextPrimary;
    sectionTitle->fontSize = 18;
    checkboxSection->addChild(sectionTitle);

    auto checkbox1 = std::make_shared<CheckboxNode>();
    checkbox1->label = "Enable dark mode";
    checkbox1->checked = true;
    checkbox1->style.widthMode = SizingMode::Hug;
    checkbox1->style.heightMode = SizingMode::Hug;
    checkbox1->style.padding = 4;
    checkbox1->onChanged = [](bool checked) {
        // Handle checkbox state change
    };
    checkboxSection->addChild(checkbox1);

    auto checkbox2 = std::make_shared<CheckboxNode>();
    checkbox2->label = "Show notifications";
    checkbox2->checked = false;
    checkbox2->style.widthMode = SizingMode::Hug;
    checkbox2->style.heightMode = SizingMode::Hug;
    checkbox2->style.padding = 4;
    checkboxSection->addChild(checkbox2);

    auto checkbox3 = std::make_shared<CheckboxNode>();
    checkbox3->label = "Auto-save changes";
    checkbox3->checked = true;
    checkbox3->style.widthMode = SizingMode::Hug;
    checkbox3->style.heightMode = SizingMode::Hug;
    checkbox3->style.padding = 4;
    checkboxSection->addChild(checkbox3);

    mainContent->addChild(checkboxSection);

    // Slider Section
    auto sliderSection = FlexNode::Column();
    sliderSection->style.widthMode = SizingMode::Flex;
    sliderSection->style.heightMode = SizingMode::Hug;
    sliderSection->style.padding = 20;
    sliderSection->style.gap = 12;

    auto sliderTitle = std::make_shared<TextNode>();
    sliderTitle->text = "Slider Components";
    sliderTitle->color = Theme::TextPrimary;
    sliderTitle->fontSize = 18;
    sliderSection->addChild(sliderTitle);

    // Horizontal slider
    auto slider1 = std::make_shared<SliderNode>();
    slider1->value = 0.7f;
    slider1->style.widthMode = SizingMode::Fixed;
    slider1->style.width = 300;
    slider1->style.heightMode = SizingMode::Hug;
    slider1->onValueChange = [](float val) {
        // Handle slider value change
    };
    sliderSection->addChild(slider1);

    // Vertical slider
    auto slider2 = std::make_shared<SliderNode>();
    slider2->value = 0.4f;
    slider2->vertical = true;
    slider2->style.widthMode = SizingMode::Hug;
    slider2->style.heightMode = SizingMode::Fixed;
    slider2->style.height = 150;
    sliderSection->addChild(slider2);

    mainContent->addChild(sliderSection);

    // Knob Section
    auto knobSection = FlexNode::Column();
    knobSection->style.widthMode = SizingMode::Flex;
    knobSection->style.heightMode = SizingMode::Hug;
    knobSection->style.padding = 20;
    knobSection->style.gap = 12;

    auto knobTitle = std::make_shared<TextNode>();
    knobTitle->text = "Knob Components";
    knobTitle->color = Theme::TextPrimary;
    knobTitle->fontSize = 18;
    knobSection->addChild(knobTitle);

    // Knobs row
    auto knobsRow = FlexNode::Row();
    knobsRow->style.widthMode = SizingMode::Flex;
    knobsRow->style.heightMode = SizingMode::Hug;
    knobsRow->style.gap = 20;

    auto knob1 = std::make_shared<KnobNode>();
    knob1->value = 0.5f;
    knob1->knobSize = 70.0f;
    knob1->onValueChange = [](float val) {
        // Handle knob value change
    };
    knobsRow->addChild(knob1);

    auto knob2 = std::make_shared<KnobNode>();
    knob2->value = 0.75f;
    knob2->knobSize = 70.0f;
    knobsRow->addChild(knob2);

    auto knob3 = std::make_shared<KnobNode>();
    knob3->value = 0.25f;
    knob3->knobSize = 70.0f;
    knobsRow->addChild(knob3);

    knobSection->addChild(knobsRow);
    mainContent->addChild(knobSection);

    // VU Meter Section
    auto vuSection = FlexNode::Column();
    vuSection->style.widthMode = SizingMode::Flex;
    vuSection->style.heightMode = SizingMode::Hug;
    vuSection->style.padding = 20;
    vuSection->style.gap = 12;

    auto vuTitle = std::make_shared<TextNode>();
    vuTitle->text = "VU Meter Components";
    vuTitle->color = Theme::TextPrimary;
    vuTitle->fontSize = 18;
    vuSection->addChild(vuTitle);

    // VU Meters row
    auto vuRow = FlexNode::Row();
    vuRow->style.widthMode = SizingMode::Flex;
    vuRow->style.heightMode = SizingMode::Hug;
    vuRow->style.gap = 20;

    // Vertical VU meters
    auto vu1 = std::make_shared<VUMeterNode>();
    vu1->setValue(0.5f);
    vu1->vertical = true;
    vu1->meterHeight = 150.0f;
    vuRow->addChild(vu1);

    auto vu2 = std::make_shared<VUMeterNode>();
    vu2->setValue(0.75f);
    vu2->vertical = true;
    vu2->meterHeight = 150.0f;
    vuRow->addChild(vu2);

    auto vu3 = std::make_shared<VUMeterNode>();
    vu3->setValue(0.95f);
    vu3->vertical = true;
    vu3->meterHeight = 150.0f;
    vuRow->addChild(vu3);

    vuSection->addChild(vuRow);

    // Horizontal VU meter
    auto vuHoriz = std::make_shared<VUMeterNode>();
    vuHoriz->setValue(0.6f);
    vuHoriz->vertical = false;
    vuHoriz->meterHeight = 300.0f;
    vuHoriz->style.widthMode = SizingMode::Fixed;
    vuHoriz->style.width = 350;
    vuSection->addChild(vuHoriz);

    mainContent->addChild(vuSection);

    // Wrap mainContent in a ScrollArea
    auto scrollArea = std::make_shared<ScrollAreaNode>();
    scrollArea->style.flex = 1.0f;
    scrollArea->style.widthMode = SizingMode::Flex;
    scrollArea->style.heightMode = SizingMode::Flex;
    scrollArea->style.backgroundColor = Theme::Background;
    scrollArea->setContent(mainContent);

    root->addChild(sidebar);
    root->addChild(scrollArea);
    
    return root;
}

int WINAPI WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nCmdShow) {
    App::getInstance().init();
    
    MochiUI::Window window("MochiUI Explorer", 1280, 800);
    window.enableMica(true);

    auto menuBar = MochiUI::MenuBarFactory::Create(MochiUI::MenuBackend::Skia);
    menuBar->addMenu("File", {
        { "New", 101, []() {
            ModernTaskDialog::showMessage(nullptr, L"MochiUI", L"New File", 
                                   L"Create a new file in the application.", 
                                   TaskDialogIcon::Information);
        } },
        { "Exit", 103, []() { 
            if (ModernTaskDialog::confirm(nullptr, L"Exit Application", 
                                   L"Are you sure you want to exit?",
                                   L"Any unsaved changes will be lost.")) {
                PostQuitMessage(0);
            }
        } }
    });
    menuBar->addMenu("Edit", {
        { "Undo", 201, []() {
            ModernTaskDialog::showWarning(nullptr, L"Undo", L"Nothing to undo",
                                   L"There are no actions to undo.");
        } }
    });
    menuBar->addMenu("View", {
        { "Theme", 301, [&window]() {
            ModernTaskDialog dialog;
            dialog.setTitle(L"Theme Settings");
            dialog.setMainInstruction(L"Choose a theme");
            dialog.setContent(L"Select your preferred color theme for the application.");
            dialog.setMainIcon(TaskDialogIcon::Information);
            dialog.addCustomButton(1, L"Dark Theme");
            dialog.addCustomButton(2, L"Light Theme");
            dialog.addCustomButton(3, L"Auto (System)");
            
            auto& switcher = ThemeSwitcher::getInstance();
            auto currentTheme = switcher.getCurrentTheme();
            if (currentTheme == ThemeType::Dark) {
                dialog.setDefaultButton(1);
            } else if (currentTheme == ThemeType::Light) {
                dialog.setDefaultButton(2);
            } else {
                dialog.setDefaultButton(3);
            }
            
            dialog.setAllowDialogCancellation(true);
            int result = static_cast<int>(dialog.show(nullptr));
            
            // Apply selected theme
            if (result == 1) {
                switcher.setTheme(ThemeType::Dark);
                window.setDarkMode(true);
                InvalidateRect((HWND)window.getNativeHandle(), NULL, TRUE);
            } else if (result == 2) {
                switcher.setTheme(ThemeType::Light);
                window.setDarkMode(false);
                InvalidateRect((HWND)window.getNativeHandle(), NULL, TRUE);
            } else if (result == 3) {
                switcher.setTheme(ThemeType::Auto);
                window.setDarkMode(switcher.isWindowsInDarkMode());
                InvalidateRect((HWND)window.getNativeHandle(), NULL, TRUE);
            }
        } }
    });
    menuBar->addMenu("Help", {
        { "About", 401, []() {
            ModernTaskDialog dialog;
            dialog.setTitle(L"About MochiUI");
            dialog.setMainInstruction(L"MochiUI Framework v1.0");
            dialog.setContent(L"A modern UI framework built with Skia and Win32.");
            dialog.setExpandedInfo(L"MochiUI combines the power of Skia's 2D graphics with "
                                  L"native Windows controls to create beautiful, performant applications.\n\n"
                                  L"Features:\n"
                                  L"\u2022 Flexbox-based layout system\n"
                                  L"\u2022 CPU-based rendering with Skia\n"
                                  L"\u2022 Modern Windows 11 styling\n"
                                  L"\u2022 Task Dialog integration");
            dialog.setFooter(L"Built with \u2764\uFE0F using Skia");
            dialog.setMainIcon(TaskDialogIcon::Information);
            dialog.setCommonButtons(TDCBF_OK_BUTTON);
            dialog.show(nullptr);
        } }
    });
    
    window.setMenuBar(std::move(menuBar));

    auto ui = CreateAppUI(1280, 800);
    window.setRoot(ui);
    window.run();
    return 0;
}
