#pragma once

// Main components header - includes all component types
#include <include/gui/Components/TextNode.hpp>
#include <include/gui/Components/CheckboxNode.hpp>
#include <include/gui/Components/SliderNode.hpp>
#include <include/gui/Components/KnobNode.hpp>
#include <include/gui/Components/VUMeterNode.hpp>
#include <include/gui/Components/ScrollAreaNode.hpp>
#include <include/gui/Components/GroupBox.hpp>
#include <include/gui/Components/TextInput.hpp>
#include <include/gui/Components/NumberInput.hpp>
#include <include/gui/Components/ComboBox.hpp>
#include <include/gui/Components/ProgressBar.hpp>
#include <include/gui/Components/GraphNode.hpp>
#include <include/gui/Components/ButtonNode.hpp>
#include <include/gui/Components/Table.hpp>
#include <include/gui/Components/ColorPicker.hpp>
#include <include/gui/Components/Calendar.hpp>
#include <include/gui/Components/IconNode.hpp>
#include <include/gui/Components/DatePicker.hpp>
#include <include/gui/Components/Popover.hpp>
#include <include/gui/Components/SwitchNode.hpp>
#include <include/gui/Components/RadioButtonNode.hpp>
#include <include/gui/Components/SeparatorNode.hpp>
#include <include/gui/Components/BadgeNode.hpp>
#include <include/gui/Components/SpinnerNode.hpp>
#include <include/gui/Components/LinkNode.hpp>
#include <include/gui/Components/TabsNode.hpp>
#include <include/gui/Components/AccordionNode.hpp>
#include <include/gui/Components/SplitterNode.hpp>
#include <include/gui/Components/ModalNode.hpp>
#include <include/gui/Components/SidebarNode.hpp>
#include <include/gui/Components/SearchInputNode.hpp>
#include <include/gui/Components/RatingNode.hpp>
#include <include/gui/Components/TooltipNode.hpp>
#include <include/gui/Components/ToastNode.hpp>
#include <include/gui/Components/SkeletonNode.hpp>
#include <include/gui/Components/BreadcrumbsNode.hpp>
#include <include/gui/Components/ToolbarNode.hpp>
#include <include/gui/Components/EmptyStateNode.hpp>
#include <include/gui/Components/StepIndicator.hpp>
#include <include/gui/Components/TagInputNode.hpp>
#include <include/gui/Components/TreeView.hpp>
#include <include/gui/Components/FilePickerNode.hpp>
#include <include/gui/Components/MultiSelectNode.hpp>
#include <include/gui/Components/LegendNode.hpp>
#include <include/gui/Components/HeatmapNode.hpp>
#include <include/gui/Components/TimelineNode.hpp>
