#include <SPHXGraphicInterface.hpp>
#include <SPHXGraphicComponents.hpp>
#include <SphereReact.hpp>
#include <core/ResourceManager.hpp>
#include <ReactUIResources.hpp>   // generated by scripts/gen_resources.ts

#include <windows.h>
#include <string>

using namespace SphereUI;

int WINAPI WinMain(HINSTANCE, HINSTANCE, LPSTR, int) {
    Application::getInstance().init();

    // Register the embedded bundle.js so res://bundle.js resolves correctly.
    InitReactUIResources();

    // ── Load JS bundle from the resource store ────────────────────────────────
    const std::string bundleSrc =
        ResourceManager::getInstance().getResourceString("res://bundle.js");

    if (bundleSrc.empty()) {
        Win32Window window("ReactUI Demo — Error", 800, 400);
        window.setDarkMode(true);
        window.enableMica(true);
        window.setRoot(MakeJSErrorScreen(
            "React",
            "Resource not found: res://bundle.js",
            "The embedded JavaScript bundle could not be loaded from the resource pack.",
            "Run `bun run bundle:demo` in modules/reactui/ to build the JS bundle from examples/App.tsx, "
            "then rebuild the CMake target so gen_resources.ts embeds it."));
        window.run();
        return 1;
    }

    // ── Evaluate the bundle with the SphereUI bridge installed ──────────────
    JavaScriptEngine engine;
    engine.init();

    auto root = RenderReactApp(engine, bundleSrc, "res://bundle.js");

    if (!root) {
        const std::string err = engine.lastError();
        Win32Window window("ReactUI Demo — JS Error", 900, 500);
        window.setDarkMode(true);
        window.enableMica(true);
        window.setRoot(MakeJSErrorScreen(
            "React",
            "JavaScript evaluation failed",
            err,
            "The bundle loaded, but the JS engine returned an evaluation error before a root node was produced.",
            engine.debugLog()));
        window.run();
        return 1;
    }

    // ── Display the React-rendered node tree ──────────────────────────────────
    Win32Window window("SphereKit - React UI Flex Lab", 1280, 800);
    window.setDarkMode(true);
    window.enableMica(true);
    window.center();
    window.setRoot(root);
    window.run();
    return 0;
}
