#include <windows.h>
#include <include/core/SkCanvas.h>
#include <include/core/SkFont.h>
#include <include/core/SkTypeface.h>
#include <include/core/SkFontMgr.h>
#include <include/ports/SkTypeface_win.h>
#include <include/gui/MochiUI.h>
#include <include/gui/Layout.hpp>
#include <include/gui/Components.hpp>
#include <include/gui/Theme.hpp>
#include <include/gui/TaskDialog.hpp>
#include <include/utils/FontManager/FontMgr.hpp>

using namespace MochiUI;

FlexNode::Ptr CreateAppUI(int width, int height) {
    auto root = FlexNode::Row();
    root->style.backgroundColor = Theme::Background;
    root->style.widthMode = SizingMode::Flex;
    root->style.heightMode = SizingMode::Flex;

    auto sidebar = FlexNode::Column();
    sidebar->style.width = 250;
    sidebar->style.widthMode = SizingMode::Fixed;
    sidebar->style.heightMode = SizingMode::Flex;
    sidebar->style.backgroundColor = Theme::Sidebar;
    sidebar->style.padding = 10;
    sidebar->style.gap = 5;

    for(int i=1; i<=8; ++i) {
        auto item = std::make_shared<TextNode>();
        item->text = "Mochi Item " + std::to_string(i);
        item->style.height = 35;
        item->style.heightMode = SizingMode::Fixed;
        item->style.widthMode = SizingMode::Flex;
        item->style.backgroundColor = Theme::Card;
        item->style.borderRadius = 6;
        item->color = Theme::TextPrimary;
        item->fontSize = 14;
        sidebar->addChild(item);
    }

    auto mainContent = FlexNode::Column();
    mainContent->style.flex = 1.0f;
    mainContent->style.widthMode = SizingMode::Flex;
    mainContent->style.heightMode = SizingMode::Flex;
    mainContent->style.padding = 40;
    mainContent->style.gap = 20;

    auto header = std::make_shared<TextNode>();
    header->text = "MochiUI Framework";
    header->style.heightMode = SizingMode::Hug;
    header->style.widthMode = SizingMode::Hug;
    header->style.padding = 5;
    header->color = Theme::TextPrimary;
    header->fontSize = 42;
    mainContent->addChild(header);

    auto hugContainer = FlexNode::Row();
    hugContainer->style.heightMode = SizingMode::Hug;
    hugContainer->style.widthMode = SizingMode::Hug;
    hugContainer->style.backgroundColor = Theme::Accent;
    hugContainer->style.padding = 10;
    hugContainer->style.borderRadius = 10;
    hugContainer->style.gap = 10;

    auto hugText = std::make_shared<TextNode>();
    hugText->text = "Autogenerated Theme Applied!";
    hugText->style.widthMode = SizingMode::Hug;
    hugText->style.heightMode = SizingMode::Hug;
    hugText->color = Theme::TextPrimary;
    hugContainer->addChild(hugText);
    
    mainContent->addChild(hugContainer);

    root->addChild(sidebar);
    root->addChild(mainContent);
    
    return root;
}

int WINAPI WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nCmdShow) {
    App::Get().init();
    
    MochiUI::Window window("MochiUI Explorer", 1280, 800);
    window.enableMica(true);

    auto menuBar = MochiUI::MenuBarFactory::Create(MochiUI::MenuBackend::Skia);
    menuBar->addMenu("File", {
        { "New", 101, []() {
            ModernTaskDialog::showMessage(nullptr, L"MochiUI", L"New File", 
                                   L"Create a new file in the application.", 
                                   TaskDialogIcon::Information);
        } },
        { "Exit", 103, []() { 
            if (ModernTaskDialog::confirm(nullptr, L"Exit Application", 
                                   L"Are you sure you want to exit?",
                                   L"Any unsaved changes will be lost.")) {
                PostQuitMessage(0);
            }
        } }
    });
    menuBar->addMenu("Edit", {
        { "Undo", 201, []() {
            ModernTaskDialog::showWarning(nullptr, L"Undo", L"Nothing to undo",
                                   L"There are no actions to undo.");
        } }
    });
    menuBar->addMenu("View", {
        { "Theme", 301, []() {
            ModernTaskDialog dialog;
            dialog.setTitle(L"Theme Settings");
            dialog.setMainInstruction(L"Choose a theme");
            dialog.setContent(L"Select your preferred color theme for the application.");
            dialog.setMainIcon(TaskDialogIcon::Information);
            dialog.addCustomButton(1, L"Dark Theme");
            dialog.addCustomButton(2, L"Light Theme");
            dialog.addCustomButton(3, L"Auto (System)");
            dialog.setDefaultButton(1);
            dialog.setAllowDialogCancellation(true);
            auto result = dialog.show(nullptr);
        } }
    });
    menuBar->addMenu("Help", {
        { "About", 401, []() {
            ModernTaskDialog dialog;
            dialog.setTitle(L"About MochiUI");
            dialog.setMainInstruction(L"MochiUI Framework v1.0");
            dialog.setContent(L"A modern UI framework built with Skia and Win32.");
            dialog.setExpandedInfo(L"MochiUI combines the power of Skia's 2D graphics with "
                                  L"native Windows controls to create beautiful, performant applications.\n\n"
                                  L"Features:\n"
                                  L"\u2022 Flexbox-based layout system\n"
                                  L"\u2022 CPU-based rendering with Skia\n"
                                  L"\u2022 Modern Windows 11 styling\n"
                                  L"\u2022 Task Dialog integration");
            dialog.setFooter(L"Built with \u2764\uFE0F using Skia");
            dialog.setMainIcon(TaskDialogIcon::Information);
            dialog.setCommonButtons(TDCBF_OK_BUTTON);
            dialog.show(nullptr);
        } }
    });
    
    window.setMenuBar(std::move(menuBar));

    auto ui = CreateAppUI(1280, 800);
    window.setRoot(ui);
    window.run();
    return 0;
}
