#include <windows.h>
#include <include/core/SkCanvas.h>
#include <include/core/SkFont.h>
#include <include/core/SkTypeface.h>
#include <include/core/SkFontMgr.h>
#include <include/ports/SkTypeface_win.h>
#include "gui/MochiUI.h"
#include "gui/Layout.hpp"
#include "gui/Components.hpp"
#include "gui/Theme.hpp"

using namespace MochiUI;

sk_sp<SkFontMgr> gFontMgr;

FlexNode::Ptr CreateAppUI(int width, int height) {
    auto root = FlexNode::Row();
    root->style.backgroundColor = Theme::Background;
    root->style.widthMode = SizingMode::Flex;
    root->style.heightMode = SizingMode::Flex;

    auto sidebar = FlexNode::Column();
    sidebar->style.width = 250;
    sidebar->style.widthMode = SizingMode::Fixed;
    sidebar->style.heightMode = SizingMode::Flex;
    sidebar->style.backgroundColor = Theme::Sidebar;
    sidebar->style.padding = 10;
    sidebar->style.gap = 5;

    for(int i=1; i<=8; ++i) {
        auto item = std::make_shared<TextNode>();
        item->text = "Mochi Item " + std::to_string(i);
        item->style.height = 35;
        item->style.heightMode = SizingMode::Fixed;
        item->style.widthMode = SizingMode::Flex;
        item->style.backgroundColor = Theme::Card;
        item->style.borderRadius = 6;
        item->color = Theme::TextPrimary;
        item->fontSize = 14;
        sidebar->addChild(item);
    }

    auto mainContent = FlexNode::Column();
    mainContent->style.flex = 1.0f;
    mainContent->style.widthMode = SizingMode::Flex;
    mainContent->style.heightMode = SizingMode::Flex;
    mainContent->style.padding = 40;
    mainContent->style.gap = 20;

    auto header = std::make_shared<TextNode>();
    header->text = "MochiUI Framework";
    header->style.heightMode = SizingMode::Hug;
    header->style.widthMode = SizingMode::Hug;
    header->style.padding = 5;
    header->color = Theme::TextPrimary;
    header->fontSize = 42;
    mainContent->addChild(header);

    auto hugContainer = FlexNode::Row();
    hugContainer->style.heightMode = SizingMode::Hug;
    hugContainer->style.widthMode = SizingMode::Hug;
    hugContainer->style.backgroundColor = Theme::Accent;
    hugContainer->style.padding = 10;
    hugContainer->style.borderRadius = 10;
    hugContainer->style.gap = 10;

    auto hugText = std::make_shared<TextNode>();
    hugText->text = "Autogenerated Theme Applied!";
    hugText->style.widthMode = SizingMode::Hug;
    hugText->style.heightMode = SizingMode::Hug;
    hugText->color = Theme::TextPrimary;
    hugContainer->addChild(hugText);
    
    mainContent->addChild(hugContainer);

    root->addChild(sidebar);
    root->addChild(mainContent);
    
    return root;
}

int WINAPI WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nCmdShow) {
    gFontMgr = SkFontMgr_New_DirectWrite();
    MochiUI::Window window("MochiUI Explorer", 1280, 800);
    window.enableMica(true);

    auto menuBar = MochiUI::MenuBarFactory::Create(MochiUI::MenuBackend::Skia);
    menuBar->addMenu("File", {
        { "New", 101, []() {} },
        { "Exit", 103, []() { PostQuitMessage(0); } }
    });
    menuBar->addMenu("Edit", {
        { "Undo", 201, []() {} }
    });
    menuBar->addMenu("View", {
        { "Theme", 301, []() {} }
    });
    
    window.setMenuBar(std::move(menuBar));

    auto ui = CreateAppUI(1280, 800);
    window.setRoot(ui);
    window.run();
    return 0;
}
